In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier

data = pd.read_csv("wine.csv", header = None)
                   #usecols=['Class', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium']) 
                                        #'Total phenols', 'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                                        #'Color intensity', 'Hue', 'OD280/OD315', 'Proline'])
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [18]:
target = data[0]
features = pd.DataFrame(data)
features = features.drop([0],axis=1)

In [21]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)
X = np.array(features)
y = np.array(target)
#neigh = KNeighborsClassifier(n_neighbors=1)
#neigh.fit(X,y)

In [53]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import scale

X = scale(X)

for i in range(50):
    classifiers = []
# метод split возвращает индексы для объектов train и test
    for train_index, test_index in kf.split(y):
        neigh = KNeighborsClassifier(n_neighbors=i+1)
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        neigh.fit(X_train, y_train)
 
    # получим 5 оптимальных классификаторов
        classifiers.append(neigh)
    
        res = cross_val_score(neigh, X, y, cv=5)
 
    print(i+1,np.mean(res))

1 0.9495238095238095
2 0.9384126984126985
3 0.943968253968254
4 0.9384126984126985
5 0.9550793650793651
6 0.9495238095238095
7 0.9665079365079364
8 0.9665079365079364
9 0.9496825396825397
10 0.9552380952380952
11 0.9552380952380952
12 0.9552380952380952
13 0.9552380952380952
14 0.9552380952380952
15 0.9607936507936508
16 0.9665079365079364
17 0.9665079365079364
18 0.9609523809523809
19 0.9607936507936508
20 0.9609523809523809
21 0.9607936507936508
22 0.9609523809523809
23 0.9607936507936508
24 0.9607936507936508
25 0.9663492063492063
26 0.9663492063492063
27 0.9663492063492063
28 0.9663492063492063
29 0.9663492063492063
30 0.9663492063492063
31 0.9663492063492063
32 0.9663492063492063
33 0.9663492063492063
34 0.9607936507936508
35 0.9663492063492063
36 0.9607936507936508
37 0.9663492063492063
38 0.9663492063492063
39 0.9663492063492063
40 0.9607936507936508
41 0.9663492063492063
42 0.9552380952380952
43 0.9663492063492063
44 0.9552380952380952
45 0.9607936507936508
46 0.9607936507936508
47 0.9663492063492063
48 0.9607936507936508
49 0.9607936507936508
50 0.9552380952380952

In [ ]:
#ответ 28